import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "../globals.css";

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/auth-context";
import SideNav from "@/modules/cms/ui/SideNav";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${pixelifySans.variable} antialiased`}
      >
        <AuthProvider>
          <div className="min-h-screen">
            <SideNav />
            <main className="md:ml-64 p-6">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
